version: '3.4'

services:

  mongodb:
    image: mongo
    restart: "no"
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    

  backend-server:
    restart: "no"
    build: .
    ports:
      - 3030:3030
volumes:
  mongo-data: